### ISSUE TITLE
Error in processBismark call to read.bismark

### ISSUE THREAD

**Issue by cemordaunt** [ben-laufer/DMRichR#1]
Hey, I got this error in the processBismark function while running DM.R:

`[DMRichR] Loading Bismark cytosine reports               06-11-2018 12:11:07 PM`
`Error in read.bismark(files = files, sampleNames = names, rmZeroCov = TRUE,  :`
`unused arguments (sampleNames = names, fileType = "cytosineReport", mc.cores = mc.cores)`
`Calls: processBismark`
`Execution halted`

I think sampleNames, fileType, and mc.cores are extra arguments. Could you remove them?

Thanks!

**Comment by ben-laufer** [comment]
Hi Charles,

Thanks for pointing this out. This error is coming from the changes made to bsseq's read.bismark function in the recent Bioconductor 3.8 release, so I have made some changes to get the processBismark working again.

6cbe90eb28891312fe0347b6c91094813389bd6f

Thanks,

Ben
