### ISSUE TITLE
can this program be used for genome hg19？

### ISSUE THREAD

**Issue by cby01** [ben-laufer/DMRichR#32]
HI,
I´m new working with DMRichR. I would lik to know if the DMRichR Suitable for reference hg19?
can I modify it to handle the Bismark cytosine reports with reference hg19？
Thanks for helping

**Comment by ben-laufer** [comment]
Hi, thanks for asking! I've added in support for hg19 to the latest version (https://github.com/ben-laufer/DMRichR/commit/ad8ce9a159168bd3a97468e1374ae013a4c1e1f8), so please try that out and let me know if you run into any problems.

**Comment by cby01** [comment]
thank you very much，I will try it ！
