### ISSUE TITLE
Install R package issue

### ISSUE THREAD

**Issue by El-Castor** [ben-laufer/DMRichR#36]
Hi,

Thanks for this work!
I want to install your R package but I have some issue when it launch the install of the 'sm' R package as you can below:

```r
** R
** inst
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for ‘sm’:
 .onLoad a échoué dans loadNamespace() pour 'tcltk', détails :
  appel : fun(libname, pkgname)
  erreur : (converti depuis l'avis) couldn't connect to display "localhost:10.0"
Erreur : le package ‘sm’ ne peut être chargé
Exécution arrêtée
ERROR: lazy loading failed for package ‘GOfuncR’
* removing ‘/opt/share/FLOCAD/userspace/cpichot/miniconda3/envs/DMRichR/lib/R/library/GOfuncR’
Erreur : Failed to install 'DMRichR' from GitHub:
  (converti depuis l'avis) installation of package ‘GOfuncR’ had non-zero exit status
```

but when I try just to install 'sm' only it work but with the same issue as warning :
```r
> BiocManager::install(c("sm"))
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.1 (2020-06-06)
Installing package(s) 'sm'
essai de l'URL 'https://cran.rstudio.com/src/contrib/sm_2.2-5.6.tar.gz'
Content type 'application/x-gzip' length 256355 bytes (250 KB)
==================================================
downloaded 250 KB

* installing *source* package ‘sm’ ...
** package ‘sm’ correctement décompressé et sommes MD5 vérifiées
** using staged installation
** libs
...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Warning in fun(libname, pkgname) :
  couldn't connect to display "localhost:10.0"
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Warning in fun(libname, pkgname) :
  couldn't connect to display "localhost:10.0"
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
Warning in fun(libname, pkgname) :
  couldn't connect to display "localhost:10.0"
** testing if installed package keeps a record of temporary installation path
* DONE (sm)

The downloaded source packages are in
	‘/tmp/RtmprNURcs/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
> 

```

So I have install the package with conda-forge channel in conda environment, but when I try to install you R package I have the same issue.

Do you have any suggestion please ?

Thanks in advance

**Comment by ben-laufer** [comment]
Hi @El-Castor, the sm package does produce some problems when installing on nodes without graphics devices and for a reason unclear to me, R will upgrade the warning into an error when installing DMRichR. You did find the workaround, which is to install it on its own first, and then install DMRichR after. 

So, within that R session, you'd just run:

```
install.packages("sm")
BiocManager::install("ben-laufer/DMRichR", update = TRUE, ask = FALSE)
```

Sometimes, particularly if you don't have a lot of the other packages, you'll need to run the second line more than once. I'm working on the dependencies to reduce the odds of this and hope to have that improvement out for the next version of the program. However, the above strategy should allow you get started now. Please let me know if you run into any other obstacles.

**Comment by El-Castor** [comment]
Hi @ben-laufer, 

thank a lot, I have try your command but I have still the same error unfortunatly. the install of the sm package work but still with the warning realted to the loss of display mode avaible.

It exist a way to block the install of th sm package install.packages("sm") when I run the install of DMRichR?

**Comment by ben-laufer** [comment]
Hi @El-Castor, when installing DMRichR, R shouldn't also try to install anything already there. I think the problems might have to do with you using conda. I generally don't use it for R, since it can produce some strange problems. Is it possible for you to try this out without conda? If you want to set up a separate environment, you can also `.libPaths()` within R to create and use a separate library folder (which is what we do over here).

**Comment by El-Castor** [comment]
Thanks, unfortunatly I cannot install anythings... I am forced to use conda environment. can you explain the .libpath() methods, I don't know how to do it ?

**Comment by ben-laufer** [comment]
You'd want to use`.libPaths()`before installing anything. The first thing to try is just running the command in R as is (`.libPaths()`) and it will tell you where your libraries are being saved, which based on what you sent before will be something like `/opt/share/FLOCAD/userspace/cpichot/miniconda3/envs/DMRichR/lib/R/library/`.

Then after that, within the command, specify an existing directory that you'd like to use. For example we use `.libPaths("/share/lasallelab/programs/DMRichR/R_4.0")`. We add this line in our scripts before we load or install any libraries. That way R will also look there for any existing libraries there and also install new ones into there.

I'm not sure how this will interact with conda, but it's worth a try. If that doesn't work, it might be worth getting in touch with the system administrators for your cluster about obtaining permissions to set up your own R libraries outside of conda.

**Comment by El-Castor** [comment]
I will try what you advice.
 I keep you posted, thank you again for your availability

**Comment by El-Castor** [comment]
I have one more question but is not related to this probleme. How I can add manually my custom genome please ?

**Comment by ben-laufer** [comment]
I think I found the solution for you:

```
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = TRUE)
BiocManager::install(ben-laufer/DMRichR")
```

I'll address the other question in a new GitHub issue to make easier for others to see.

**Comment by El-Castor** [comment]
hi @ben-laufer, 

Thans a lot for your help and your reactivity. The last command that you give me works, instead with some warning (as you can see below) but I think it should be ok. Do you think it can be introduce some bias or troubleshooting during the analysis?

```r
* installing *source* package ‘DMRichR’ ...
** using staged installation
** R
** exec
** byte-compile and prepare package for lazy loading
Warning: pas de variable DISPLAY, donc Tk n'est pas disponible
Warning: replacing previous import ‘BiocGenerics::Position’ by ‘ggplot2::Position’ when loading ‘DMRichR’
Warning: replacing previous import ‘PerformanceAnalytics::textplot’ by ‘gplots::textplot’ when loading ‘DMRichR’
Warning: replacing previous import ‘gplots::space’ by ‘rtracklayer::space’ when loading ‘DMRichR’
Warning: replacing previous import ‘gt::html’ by ‘rvest::html’ when loading ‘DMRichR’
Note: wrong number of arguments to 'ceiling' 
Note: wrong number of arguments to 'ceiling' 
Note: wrong number of arguments to 'ceiling' 
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Warning: pas de variable DISPLAY, donc Tk n'est pas disponible
Warning: replacing previous import ‘BiocGenerics::Position’ by ‘ggplot2::Position’ when loading ‘DMRichR’
Warning: replacing previous import ‘PerformanceAnalytics::textplot’ by ‘gplots::textplot’ when loading ‘DMRichR’
Warning: replacing previous import ‘gplots::space’ by ‘rtracklayer::space’ when loading ‘DMRichR’
Warning: replacing previous import ‘gt::html’ by ‘rvest::html’ when loading ‘DMRichR’
** testing if installed package can be loaded from final location
Warning: pas de variable DISPLAY, donc Tk n'est pas disponible
Warning: replacing previous import ‘BiocGenerics::Position’ by ‘ggplot2::Position’ when loading ‘DMRichR’
Warning: replacing previous import ‘PerformanceAnalytics::textplot’ by ‘gplots::textplot’ when loading ‘DMRichR’
Warning: replacing previous import ‘gplots::space’ by ‘rtracklayer::space’ when loading ‘DMRichR’
Warning: replacing previous import ‘gt::html’ by ‘rvest::html’ when loading ‘DMRichR’
** testing if installed package keeps a record of temporary installation path
* DONE (DMRichR)

```
Looking forward to hearing from you.

**Comment by ben-laufer** [comment]
Great, that means it's working. You don't have to worry about those warnings, they don't affect anything.

Here's the information for the sample info sheet: https://github.com/ben-laufer/DMRichR#the-design-matrix-and-covariates
