### ISSUE TITLE
Custom genomes

### ISSUE THREAD

**Issue by ben-laufer** [ben-laufer/DMRichR#37]
Hello @El-Castor, to answer your question about custom genomes from https://github.com/ben-laufer/DMRichR/issues/36, there are a few possibilities. If you can find a `BSgenome`, a `TxDb`, and a `org.db` on [Bioconductor](https://www.bioconductor.org/packages/release/data/annotation/) then you only need to add the reference to them into the ["Setup annotation databases" section of DM.R](https://github.com/ben-laufer/DMRichR/blob/master/exec/DM.R#L104) by copying the style used. If those don't exist, then you can try to manually make them using other existing external databases. Alternatively, you can further modify DM.R to LiftOver to a closely related genome after the block and DMR calling. Finally, if you don't need the downstream enrichment analyses and data visualizations, and just want the coverage filtering, block calling, and DMR calling, then the simplest route is to delete the other sections from the script, since the first parts don't rely on those databases.

**Comment by El-Castor** [comment]
Hi @ben-laufer , 

I have already all this R object prepared (Bsgenome, TxDB and or.db object for my custom genome). I will check the section "Setup annotation databases" section of DM.R". Thanks you

**Comment by ben-laufer** [comment]
Glad to hear you already have the R objects. They don't need to be on biocondcutor. You just have to modify the script at the spot I mentioned to load them and assign them:

```
goi <- BSgenome
TxDb <- TxDb
annoDb <- "org.db"
```

**Comment by El-Castor** [comment]
Hi @ben-laufer, 
Sorry I know that I have said that I have all the R object but It loss the org.db R object... Do you know where I can find a documentation to build it? I didn't find it on the main doc of AnnoDb to build it with a custom genome
