### ISSUE TITLE
Error in createCommonDmrsHeatmap / hclust

### ISSUE THREAD

**Issue by semenko** [ben-laufer/DMRichR#48]
Thanks for the awesome software! 

In the dataset I'm trying this out on, I'm getting this crash in _createCommonDmrsHeatmap_

Running this with roughly:
`Rscript --vanilla exec/DM.R --genome mm10 --coverage 10 --minCpGs 5 --maxPerms 8 --maxBlockPerms 8 --cutoff '0.1' --testCovariate Diagnosis --sexCheck FALSE --ensembl FALSE --cores 32 --GOfuncR TRUE --cellComposition FALSE`

Error:

[DMRichR] Learning features of DMRs for Diagnosis       01-04-2021 10:05:29 PM
 Training random forest (RF) model for DMR ranking...Done.
 Training support vector machine (SVM) model for DMR ranking...Done.
 1% of 769 total DMRs is 8 and less than 10.
 Finding common DMRs in top 10 DMRs (instead of in top 1%) in RF and SVM predictor ranking lists.
 Beginning DMR annotation...
... preparing features information...             2021-04-01 10:05:41 PM
... identifying nearest features...               2021-04-01 10:05:41 PM
... calculating distance from peak to TSS...      2021-04-01 10:05:42 PM
... assigning genomic annotation...               2021-04-01 10:05:42 PM
... adding gene annotation...                     2021-04-01 10:05:44 PM
'select()' returned 1:1 mapping between keys and columns
... assigning chromosome lengths                  2021-04-01 10:05:44 PM
... done...                                       2021-04-01 10:05:44 PM
 Generating HTML report...
 Beginning DMR annotation...
... preparing features information...             2021-04-01 10:05:44 PM
... identifying nearest features...               2021-04-01 10:05:44 PM
... calculating distance from peak to TSS...      2021-04-01 10:05:44 PM
... assigning genomic annotation...               2021-04-01 10:05:44 PM
... adding gene annotation...                     2021-04-01 10:05:46 PM
'select()' returned 1:1 mapping between keys and columns
... assigning chromosome lengths                  2021-04-01 10:05:46 PM
... done...                                       2021-04-01 10:05:47 PM
 Beginning DMR annotation...
... preparing features information...             2021-04-01 10:05:47 PM
... identifying nearest features...               2021-04-01 10:05:47 PM
... calculating distance from peak to TSS...      2021-04-01 10:05:47 PM
... assigning genomic annotation...               2021-04-01 10:05:47 PM
... adding gene annotation...                     2021-04-01 10:05:49 PM
'select()' returned 1:1 mapping between keys and columns
... assigning chromosome lengths                  2021-04-01 10:05:49 PM
... done...                                       2021-04-01 10:05:49 PM
**Error in hclust(d, method = method) : must have n >= 2 objects to cluster
Calls: <Anonymous> ... createCommonDmrsHeatmap -> <Anonymous> -> cluster_mat -> hclust
In addition: There were 17 warnings (use warnings() to see them)
Execution halted**

**Comment by ben-laufer** [comment]
Hi @semenko,

Would you mind running this section of code again to retrieve the output of `warnings()`? 

This can be accomplished by running the following code in an interactive R session. 

```
suppressPackageStartupMessages(require("DMRichR", quietly = TRUE))
load("RData/settings.RData")
DMRichR::annotationDatabases(genome)
load("RData/DMRs.RData")
load("RData/bsseq.RData")

methylLearnOutput <- DMRichR::methylLearn(bs.filtered.bsseq = bs.filtered.bsseq,
                                          sigRegions = sigRegions,
                                          testCovariate = testCovariate,
                                          TxDb = TxDb,
                                          annoDb = annoDb,
                                          topPercent = 1,
                                          output = "all",
                                          saveHtmlReport = TRUE)

warnings()
```

Also, as a side note, when running `DM.R` you can set coverage to 1 (even for deeply sequenced datasets), since the smoothing will give a higher weight to sites with higher coverage, and this change could give you more CpGs to assay (and thus more DMRs).

**Comment by semenko** [comment]
Thanks for your help! I was actually getting an ~overwhelming numer of DMRs previously, so I bumped up the cutoff (not coverage) to 0.1.

Here are the warnings:
<pre>
...
Error in hclust(d, method = method) : must have n >= 2 objects to cluster
In addition: There were 17 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In addShadowsAndGetImp(decReg, runs) :
  getImp result contains NA(s) or NaN(s); replacing with 0(s), yet this is suspicious.
2: In addShadowsAndGetImp(decReg, runs) :
  getImp result contains NA(s) or NaN(s); replacing with 0(s), yet this is suspicious.
...

 (repeats 17 times)
</pre>

**Comment by ben-laufer** [comment]
Unfortunately, those warnings also occur on successful runs. I think we will have to go deeper into the function to get the data being used for the heatmap. 

Would you mind loading the RData and then running the function code (https://github.com/ben-laufer/DMRichR/blob/master/R/methylLearn.R), after assigning the variables from lines 43-50? I think if you run everything up until line 296, we can inspect the `commonDmrs` object and the`heatmapData` matrix.  Then, would you mind sharing that RData or a printout of both? We can do that over e-mail if you don't want it posted on GitHub.

It would also help to know if you ran into this issue with your earlier run that generated more DMRs and to know if this occurs when you set coverage to 1 (which could give some more DMRs, but probably not nearly as many as when the cuttoff is 0.05).

**Comment by semenko** [comment]
(Unrelated: thanks for all the recent documentation updates to the code!)

Finally have some more bandwidth to debug this further; I've run into some troubles loading this manually in methylLearn.R -- I can share the RData if that's helpful.

This still reproduces with the current master (version 1.7) and bleeding-edge versions of everything (R 4.0.5 and all updated packages). With `--coverage 1` the error disappears, though it looks like it errors out near the last line of the DM.R script at https://github.com/ben-laufer/DMRichR/blob/master/R/DM.R#L851

```
[DMRichR] Summary                                        
30-04-2021 06:18:37 AM
Summary: There are 7205 (11% hypermethylated, 89% hypomethylated) from 113103 background regions consisting of 20781018 CpGs assayed at 1x coverage
Error in if (sum(blocks$pval < 0.05) > 0 & length(blocks) != 0) { :
  missing value where TRUE/FALSE needed
Calls: <Anonymous>
```

**Comment by ben-laufer** [comment]
I think the problem with methylLearn is related to the high coverage setting. Would you mind sharing the RData for that? You can send it to my e-mail if you don't want to post it on GitHub (blaufer @ ucdavis.edu)

I think the other error you're getting is from not having any blocks, which is causing an error with printing the summary, which is a separate small bug I'll fix in the near future, but thankfully the pipeline is done at that point.

**Comment by semenko** [comment]
Here's that run's RData & log: https://wustl.box.com/v/dmrichr-bug-48

**Comment by ben-laufer** [comment]
Thanks for sharing the data. I've had a chance to look into this. The problem you're running into is that there is only 1 DMR in common between the top 10 DMRs selected by the two algorithms, so when `createHtmlReport()` is called from within `methylLearn()` the heatmap can't be plotted because it requires more than 1 DMR to cluster, which explains the "must have n >= 2 objects to cluster" error.  I haven't seen this scenario before, since usually there is better overlap, but this could be coming about from the sample size (n =4) and number of features.

Two options for moving forward, are:
1) Setting saveHtmlReport = FALSE for `methylLearn()`
2) Using the other run with the default coverage settings

Hopefully this helps, but let me know if you run into any other difficulties.
