### ISSUE TITLE
error Block analysis has produced an error 

### ISSUE THREAD

**Issue by sashulkaSh** [ben-laufer/DMRichR#62]
Hello!
This is my run:
call="Rscript \
--vanilla \
/home/aleksa120396/miniconda3/envs/r4/lib/R/library/DMRichR/exec/DM.R \
--genome hg38 \
--coverage 2 \
--perGroup '0.75' \
--minCpGs 5 \
--maxPerms 10 \
--maxBlockPerms 10 \
--cutoff '0.05' \
--testCovariate Diagnosis \
--sexCheck FALSE \
--GOfuncR FALSE \
--EnsDb FALSE \
--cores 65"

I had a permanent error with the chrM - "`...Chromosome chrM: Warning: Block analysis has produced an error`". I removed chrM from the data, only 22+X+Y in my data. The error was repeated, but with a different chromosome:

```
Beginning permutation 1
...Chromosome chr1: Warning: Block analysis has produced an error

<...>

Beginning permutation 1
...Chromosome chr1: Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': singular matrix in 'backsolve'. First zero in diagonal [3]
Calls: <Anonymous> ... t -> tcrossprod -> backsolve -> .handleSimpleError -> h
In addition: Warning message:
In dir.create("RData") : 'RData' already exists
Execution halted
53275
```

what is the problem?
and a small question: why is no intermediate data saved?..

**Comment by ben-laufer** [comment]
Hi @sashulkaSh, can you confirm that you are using genome-cytosine reports and not another format: https://www.benlaufer.com/DMRichR/articles/DMRichR.html#cytosine-reports

Also, try changing the number of cores to somewhere between 10-20. Finally, DMRichR does save intermediate data in the RData folder.

**Comment by sashulkaSh** [comment]
Hello!

this is head:
chr1	    10469	+	   1	   1	CG	CGC
chr1	    10471	+	   1	   1	CG	CGG
chr1	    10484	+	   1	   1	CG	CGG
chr1	    10489	+	   1	   2	CG	CGC
chr1	    10493	+	   1	   3	CG	CGC
chr1	    10497	+	   3	   1	CG	CGG
chr1	    10525	+	   8	   0	CG	CGC
chr1	    10542	+	   8	   0	CG	CGA
chr1	    10563	+	   7	   1	CG	CGC
chr1	    10571	+	   8	   0	CG	CGC


in RData only 2 files: bismark.RData and settings.RData

does the number of cores make that much of a difference?

**Comment by ben-laufer** [comment]
Yes, the number of cores can make a difference. 

If lowering the number of cores doesn't work, then you can try loading the RData and manually running the `bs.filtered` object through `dmrseq::dmrseq()`.
