### ISSUE TITLE
 style specified by 'UCSC' error

### ISSUE THREAD

**Issue by farmohh** [ben-laufer/DMRichR#64]
Dear Ben,
Thank you for your help.

I get an erorr using DMRichR::processBismark() as follow. 

Assigning sample metadata with Diagnosis as factor of interest...
DataFrame with 4 rows and 1 column
         Diagnosis
          <factor>
sample10   lowc   
sample11   lowc   
sample22   normalc
sample24   normalc
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'unique': error in evaluating the argument 'y' in selecting a method for function 'intersect': The style specified by 'UCSC' does not have a compatible entry for the species Caenorhabditis_elegans - Copy

Here is the head of my cytosine report file for one of the samples: 
scaffold_135    163     +       0       0       CG      CGA
scaffold_135    164     -       0       0       CG      CGG
scaffold_135    479     +       0       0       CG      CGA
scaffold_135    480     -       0       0       CG      CGG
scaffold_135    523     +       0       0       CG      CGA
scaffold_135    524     -       0       0       CG      CGC
scaffold_135    572     +       0       0       CG      CGG
scaffold_135    573     -       0       0       CG      CGA
scaffold_135    947     +       0       0       CG      CGT
scaffold_135    948     -       0       0       CG      CGC

Here is the metadat xlsx file: 

Name	Diagnosis
sample10	lowc
sample11	lowc
sample22	normalc
sample24	normalc

Here is the tree structure for the cytosine reports and design matrix:

│   ├── sample10_bismark_bt2.deduplicated.bismark.cov.gz.CpG_report.txt.gz
│   ├── sample11_bismark_bt2.deduplicated.bismark.cov.gz.CpG_report.txt.gz
│   ├── sample22_bismark_bt2.deduplicated.bismark.cov.gz.CpG_report.txt.gz
│   ├── sample24_bismark_bt2.deduplicated.bismark.cov.gz.CpG_report.txt.gz
│   ├── sample_info.xlsx

**Comment by farmohh** [comment]
Hi again, 
I changed my computer, and it is working now. Thank you.

**Comment by hmyh1202** [comment]
@farmohh How to only do DMR  analysis ? can you show me a example ?
