### ISSUE TITLE
For the coverage?

### ISSUE THREAD

**Issue by hmyh1202** [ben-laufer/DMRichR#65]
Hello,
 
Nice  tools for BS-seq data analysis.

IMy question is can I use >4x CpG  sites for DMR analysis ? 

The best!

**Comment by hmyh1202** [comment]
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'nrow': invalid 'description' argument
Calls: <Anonymous> ... readUTF8 -> readLines -> file -> .handleSimpleError -> h
In addition: Warning message:
In unzip(xlsxFile, exdir = xmlDir) : error 1 in extracting from zip file
Execution halted

**Comment by hmyh1202** [comment]
[DMRichR] Selecting annotation databases                 23-09-2022 08:47:51 AM
Loading BSgenome.Hsapiens.UCSC.hg38.masked
Loading TxDb.Hsapiens.UCSC.hg38.knownGene
Loading org.Hs.eg.db
Saving Rdata...

[DMRichR] Processing Bismark cytosine reports            23-09-2022 08:47:53 AM
Selecting files...
Reading cytosine reports...
[read.bismark] Parsing files and constructing valid loci ...
Done in 87.6 secs
[read.bismark] Parsing files and constructing 'M' and 'Cov' matrices ...
Done in 35.3 secs
[read.bismark] Constructing BSseq object ...
Assigning sample metadata with Diagnosis as factor of interest...
DataFrame with 2 rows and 3 columns
             Diagnosis       Age      Sex
              <factor> <numeric> <factor>
sample1 Idiopathic_ASD        20        F
sample2 Control               20        F
Checking sex of samples...
Error: number of cluster centres must lie between 1 and nrow(x)
Execution halted
193

**Comment by hmyh1202** [comment]
Error in dmrseq::dmrseq(bs = bs.filtered, cutoff = cutoff, minNumRegion = minCpGs,  :
  At least one group has only one sample! Replicates are required to run dmrseq.
Calls: <Anonymous> -> <Anonymous>
Execution halted

**Comment by ben-laufer** [comment]
Hi @hmyh1202,

The `--coverage` argument lets you set the CpG coverage cut-off. The default is 1 and is what I recommend to use even for higher coverage projects. 

The message for the error is letting you know the issue it's running into. It seems like one of your groups only has 1 sample, and this approach requires biological replicates. If your groups should have more than one sample, have a look at your design matrix for any formatting differences in the group names (i.e. an extra space).
