### ISSUE TITLE
Large candidate regions with more than 1000 CpGs detected

### ISSUE THREAD

**Issue by semenko** [ben-laufer/DMRichR#68]
Thanks for making DMRichR!

In one exploratory analysis I have, I ran into this warning:

```
[DMRichR] Testing for DMRs with dmrseq                   22-03-2023 10:45:04 AM
Performing a global test of H0: no difference among 4 groups (assuming the test covariate Diagnosis is a factor).
Parallelizing using 8 workers/cores (backend: BiocParallel:MulticoreParam).
Computing on 1 chromosome(s) at a time.

Detecting candidate regions with coefficient larger than 0.05 in magnitude.
...Chromosome chr1: Smoothed (1.21 min). Note: Large candidate regions with more than 1000 CpGs detected. If you'd like to detect large-scale blocks, set block=TRUE. If you'd like to detect local DMRs, it is recommended to decrease the values of bpSpan, minInSpan, and/or maxGapSmooth increase computational efficiency.
```

This specific warning comes from a helper function in dmrseq: https://github.com/kdkorthauer/dmrseq/blob/master/R/helper_functions.R#L573

Unfortunately, afterwards DMRichR consumes lots of RAM (~400+GB) and usually gets oomkilled. 

Is there an easy way to pass through `block=TRUE` as suggested to dmrseq, or have you run into this issue before?

**Comment by ben-laufer** [comment]
Hi @semenko, some of this is related to: https://github.com/ben-laufer/DMRichR/issues/56#issuecomment-869840878

I'd just recommend running [this part of dmrseq](https://bioconductor.org/packages/devel/bioc/vignettes/dmrseq/inst/doc/dmrseq.html#43_Detecting_large-scale_methylation_blocks ) for your analysis and skipping the DMRs.
