### ISSUE TITLE
Cannot install  this package "ben-laufer / DMRichR" with error information

### ISSUE THREAD

**Issue by DengEr-1993** [ben-laufer/DMRichR#69]
Hi Sir,

I just want  to use this package to visualise the methylation calling result.

I think your sample visualization for CpG count matrix is beautiful.

But when I tried to install it with below tutorial:

```
if(!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
if(!requireNamespace("remotes", quietly = TRUE))
  install.packages("remotes")
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = TRUE)
BiocManager::install("ben-laufer/DMRichR")
```

The error information appeared:
```
> BiocManager::install("ben-laufer/DMRichR")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")'
for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.16 (BiocManager 1.30.20), R 4.2.1 (2022-06-23 ucrt)
Installing github package(s) 'ben-laufer/DMRichR'
Downloading GitHub repo ben-laufer/DMRichR@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/ben-laufer/DMRichR/tarball/HEAD'
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.2.1/library
  packages:
    boot, class, cluster, codetools, foreign, MASS, Matrix, mgcv, nlme, nnet, rpart, spatial, survival
Old packages: 'BiocParallel', 'cli', 'XML'
Update all/some/none? [a/s/n]: 
n
```

I also failed to install it manually. 

Can you give me some advice.  I don't know if it is OK for me to use the source code of this package only.

**Comment by ben-laufer** [comment]
This error doesn't seem to be specific to DMRichR. It looks to me like you weren't able to download from GitHub. Can you test this by trying to download a different package from GitHub?

**Comment by DengEr-1993** [comment]
> This error doesn't seem to be specific to DMRichR. It looks to me like you weren't able to download from GitHub. Can you test this by trying to download a different package from GitHub?

@ben-laufer  Thanks, I can install this pacakge on my mac.  Maybe I don't have the permission on windows PC.
