### ISSUE TITLE
Installation compatibility issues with BioCManager and r@4.1.x

### ISSUE THREAD

**Issue by perrymil** [ben-laufer/DMRichR#70]
Hi,

The installation instructions suggest using r@4.1.x

Should I be using BiocManager 3.14? 

The instructions say to use the latest BiocManager 

"make sure that you have the [latest version of bioconductor](https://www.bioconductor.org/install/)"

`> if(!requireNamespace("BiocManager", quietly = TRUE))
+   install.packages("BiocManager")
> if(!requireNamespace("remotes", quietly = TRUE))
  install.packages("remotes")
> Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = TRUE)
> BiocManager::install("ben-laufer/DMRichR")
Error: Bioconductor version '3.16' requires R version '4.2'; use
  `BiocManager::install(version = '3.14')` with R version 4.1; see
  https://bioconductor.org/install
> BiocManager::install(version = "3.17")
Error: Bioconductor version '3.17' requires R version '4.3'; use
  `BiocManager::install(version = '3.14')` with R version 4.1; see
  https://bioconductor.org/install`

**Comment by perrymil** [comment]
I tried it with the older BiocManager 3.14 to match R@4.1.2 requirements, and it failed to install the dependency ggtree for ChIPseeker

I could possible investigate further, but I wanted to check with you about how you go about installing this?

What OS have you tested this on? ubuntu?

**Comment by ben-laufer** [comment]
Hi @perrymil, it was last tested with R 4.1 and Bioconductor version 3.14. GitHub actions showed that it could be installed on MacOS, Ubuntu, and Windows.

**Comment by perrymil** [comment]
Hi Ben,

That makes sense, we are running centos7 on our cluster so the underlying dependencies versions and whatnot are different.

I might be able to help get this package working with spack on our cluster with a little bit of your assistance. 

Do you have a package dependency list with version #'s that I can use as a starting point?

I found this list of dependencies:

`
R (>= 3.5.0),
  dmrseq,
  bsseq
biocViews:
Imports: 
    BiocGenerics,
    Boruta,
    CMplot,
    ChIPseeker,
    GOfuncR,
    GenomeInfoDb,
    GenomicRanges,
    broom,
    enrichR,
    ggplot2,
    gplots,
    gt,
    lsmeans,
    openxlsx,
    rGREAT,
    rtracklayer,
    sigFeature,
    RColorBrewer,
    glue,
    grDevices,
    graphics,
    parallel,
    pheatmap,
    R2HTML,
    LOLA,
    PerformanceAnalytics,
    hablar,
    AnnotationHub,
    viridis,
    ggsci,
    minfi,
    Hmisc,
    data.table,
    BiocParallel,
    plyranges,
    wesanderson,
    dplyr,
    forcats,
    stringr,
    tidyr,
    purrr,
    tibble,
    readxl,
    readr,
    ensembldb,
    rrvgo,
    Glimma,
    BiocManager,
    magrittr,
    rlang,
    GenomicFeatures,
    DelayedMatrixStats,
    IRanges,
    stats,
    utils,
    tidyselect,
    Biobase,
    S4Vectors,
    bumphunter,
    genefilter,
    methylCC,
    PCAtools,
    scales
Suggests:
  IlluminaHumanMethylationEPICanno.ilm10b4.hg19,
  FlowSorted.Blood.EPIC,
  ExperimentHub,
  FDb.InfiniumMethylation.hg19,
  FlowSorted.Blood.450k,
  FlowSorted.CordBlood.450k,
  FlowSorted.CordBloodCombined.450k,
  FlowSorted.DLPFC.450k,
  IlluminaHumanMethylationEPICmanifest,
  knitr,
  markdown,
  rmarkdown,
  optparse,
  simpleCache,
  qvalue
  `
  
  It would help to know what specific versions of those packages your working environment has, but I should be able to start with this list to build a spack package.

**Comment by ben-laufer** [comment]
DMRichR shouldn't depend on specific package versions. It sounds like you were close with the R 4.1 and Bioconductor 3.14. Did you try manually installing ggtree first, either through BiocManager or GitHub?
