### ISSUE TITLE
Error in CMplot: :CMplot

### ISSUE THREAD

**Issue by f6v** [ben-laufer/DMRichR#72]
Hi,

I get the following error when running the workflow:
<img width="789" alt="image" src="https://github.com/ben-laufer/DMRichR/assets/13019221/a04f68d4-6445-46de-a33a-7bd0c77d061e">

Was the analysis interrupted by the error, or was it ignored? I mean, would I get all the results regardless (I don't know what to expect in the outputs since I'm running it for the first time)?

Thanks in advance!

EDIT:

I don't get any of the enrichment plots, so I guess the program finishes prematurely.

**Comment by ben-laufer** [comment]
Thanks for letting me know about this @f6v. This issue was caused by the renaming of an argument in the latest version of the CMplot package. I've updated DMRichR to fix this (83fbc23), so give the latest version a try.
