### ISSUE TITLE
Can I use this package for RRBS data & issue with running DMRichR::DM.R

### ISSUE THREAD

**Issue by MiaSands** [ben-laufer/DMRichR#76]
Hello,

Thank you for developing this convenient package for defining DMRs! 

My first question is that if this package applies to RRBS data.

My second question is that I tried to run the following code:
DMRichR::DM.R(genome=c("mm10"),testCovariate = "Treatment", adjustCovariate = c("Exposure"), sexCheck = FALSE, cores = 20, coverage = 2, perGroup =  0.75, minCpGs =  5,cutoff = 0.05,EnsDb = FALSE, GOfuncR = TRUE,cellcompostion = FALSE). 

I kept getting the error "Error in DMRichR::DM.R(genome = c("mm10"), testCovariate = "Treatment",  : unused argument (cellcompostion = FALSE)".  

Do you have any advice for how to resolve this error?

Thank you for your time!

**Comment by ben-laufer** [comment]
Hi @MiaSands, can you remove the `cellcomposition` argument and give the latest version of DMRichR a try?

Also, the package does work with RRBS data. You many need to optimize the parameters in the [call to `dmrseq()` ](https://github.com/ben-laufer/DMRichR/blob/master/R/DM.R#L288) based on the discussions in the issues section of the dmrseq GitHub and omit the [blocks section](https://github.com/ben-laufer/DMRichR/blob/master/R/DM.R#L184).

**Comment by MiaSands** [comment]
Thanks for the advice. I fixed the problem by reinstalling R and I will give it a try on my RRBS data.
