### ISSUE TITLE
DMRichR::annotationDatabases()

### ISSUE THREAD

**Issue by bazyliszek** [ben-laufer/DMRichR#77]
Hi Ben, 
We needed to make one custom genome that was missing for the tool.
 
In DMRichR, all the necessary packages and dependencies are being installed when the following command is being executed:
BiocManager::install("ben-laufer/DMRichR") and all subsequent calls of functions are done as such: e.g. DMRichR::annotationDatabases().  So we imagine that it is referring every time to DMRichR that was installed by BiocManager. If so, then when we edit the code lines of annotationDatabases.R for the custom genome, how do we tell DMRichR to read the file we edited, and not the file it downloaded from BiocManager? Kindly let us know if we explained it well enough. Maybe a small description could be great to add.  Thank you,

Best wishes,
Marcin & Wassim

**Comment by ben-laufer** [comment]
Hi @bazyliszek, for a custom genome you are correct that you'd need to modify `DMRichR::annotationDatabases()`. This would involve forking the repository, modifying the function, and then using your version (e.g. `BiocManager::install("bazyliszek/DMRichR")`. 

For modifying the function, you'd add mention of your genome and the databases [here](https://github.com/ben-laufer/DMRichR/blob/master/R/annotationDatabases.R#L66) and [here](https://github.com/ben-laufer/DMRichR/blob/master/R/annotationDatabases.R#L138) by copying the format of the above parts. You'd also have to modify `DM.R()` to include your genome [here](https://github.com/ben-laufer/DMRichR/blob/master/R/DM.R#L87) and modify [`getCpGs()`](https://github.com/ben-laufer/DMRichR/blob/master/R/annotate.R#L232).

**Comment by bazyliszek** [comment]
Great @ben-laufer . We have used this strategy indeed, so that is good that agree with us. We will contribute with another species soon so DMRichR will be more accessible.  It would also be awesome to have some recipes for HPC that do not have internet access (strict GDPR).
