### ISSUE TITLE
MethylDackel implementation

### ISSUE THREAD

**Issue by bazyliszek** [ben-laufer/DMRichR#78]
Is it also possible to use MethylDacker files output instead of Bismark?  https://github.com/dpryan79/MethylDackel
Maybe there is a way that DMRichR-compatible cytosine reports from methyldackel already? 
In the Bismark cytosine report file, you have the following columns: "chromosome, position, strand, count methylated, count non-methylated, C-context, trinucleotide context". Methyldackel bedGraph file already contains columns 1, 2, 3 and 4. 

By the way one of the link is not active in the repro: https://github.com/FelixKrueger/Bismark/tree/master/Docs#optional-genome-wide-cytosine-report-output

**Comment by ben-laufer** [comment]
Hi @bazyliszek, the cytosine reports are processed by `DMRichR::processBismark()`, which uses `bsseq::read.bismark()`. I'm not familiar with MethylDackel, but I'd recommend having a look over the "File formats section" of the `bsseq::read.bismark()` documentation to learn more. You can always fork DMRichR and modify [`DMRichR::processBismark()`](https://github.com/ben-laufer/DMRichR/blob/master/R/processBismark.R).

**Comment by bazyliszek** [comment]
Thank you for your thoughts. @wassimsalam01 forked it and will have a look further https://github.com/wassimsalam01/DMRichR   We found that Bismarck behaved a bit different from MethylDackel so we were a bit concerned, and also because of this paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9465269/
